### ISSUE TITLE
Submit envoy-proxy and cilium-proxy to Factory

### ISSUE THREAD

**Issue by vadorovsky** [kubic-project/issues#4]
Submit:

- envoy-proxy
- cilium-proxy

to devel:kubic and openSUSE:Factory as soon as the build in:

https://build.opensuse.org/project/show/home:mrostecki:branches:devel:kubic

will become green **without** any other package links.

Necessity of any package link = something else needs to be submitted to Factory and this issue is blocked!

**Comment by vadorovsky** [comment]
Blocked by:
https://github.com/kubic-project/issues/issues/3
https://github.com/kubic-project/issues/issues/2
https://github.com/kubic-project/issues/issues/1

**Comment by vadorovsky** [comment]
Done

**Comment by aikchar** [comment]
I can't find Envoy or Cilium in OBS [openSUSE:Factory](https://build.opensuse.org/project/show/openSUSE:Factory) project. Were they removed? If not, how do I search for them? Thanks.
